CREATE TABLE "USERS" (
  "USER_ID" integer UNIQUE PRIMARY KEY NOT NULL,
  "EMAIL" varchar,
  "LOGIN" varchar,
  "NAME" varchar,
  "BIRTHDAY" day
);

CREATE TABLE "FRIENDS" (
  "USER_ID" integer PRIMARY KEY,
  "FRIEND_ID" integer,
  "STATUS" boolean
);

CREATE TABLE "LIKES" (
  "FILM_ID" integer UNIQUE PRIMARY KEY,
  "USER_ID" integer
);

CREATE TABLE "FILM_GENRES" (
  "FILM_ID" integer,
  "GENRE_ID" integer
);

CREATE TABLE "GENRES" (
  "GENRE_ID" integer,
  "GENRE_NAME" varchar
);

CREATE TABLE "Films" (
  "FILM_ID" integer UNIQUE PRIMARY KEY NOT NULL,
  "FILM_NAME" varchar,
  "DESCRIPTION" varchar,
  "RELEASE_DATE" date,
  "DURATION" integer,
  "MPA_ID" integer
);

CREATE TABLE "MPA" (
  "MPA_ID" integer UNIQUE PRIMARY KEY NOT NULL,
  "MPA_NAME" varchar
);

COMMENT ON COLUMN "USERS"."USER_ID" IS 'Number';

COMMENT ON COLUMN "Films"."FILM_ID" IS 'Number';

ALTER TABLE "FRIENDS" ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "FRIENDS" ADD FOREIGN KEY ("FRIEND_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "LIKES" ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "LIKES" ADD FOREIGN KEY ("FILM_ID") REFERENCES "Films" ("FILM_ID");

ALTER TABLE "MPA" ADD FOREIGN KEY ("MPA_ID") REFERENCES "Films" ("MPA_ID");

ALTER TABLE "FILM_GENRES" ADD FOREIGN KEY ("FILM_ID") REFERENCES "Films" ("FILM_ID");

ALTER TABLE "GENRES" ADD FOREIGN KEY ("GENRE_ID") REFERENCES "FILM_GENRES" ("GENRE_ID");
